#
# General redis container
#
redis:
    image: redis:latest
    hostname: redis
    ports:
        - 6379

#
# General mongodb container
#
mongo:
    image: mongo:latest
    command: ["mongod", "--smallfiles"]
    hostname: mongo
    ports:
        - 27017

#
# General nats container
#
nats:
    image: nats:latest
    hostname: nats
    ports:
        - 4222

