#
# Service Discovery - Consul
#

consul-agent:
    image: progrium/consul
    command: -server -bootstrap -node consul
    hostname: consul-agent
    ports:
        - 8400:8400 
        - 127.0.0.1:8500:8500 
        - 172.17.42.1:8500:8500 
        - 172.17.42.1:53:53/udp
#
# Service Discovery - Registrator
#
registrator:
    command: -retry-interval 1000 -retry-attempts 5 -internal consul://172.17.42.1:8500
    image: gliderlabs/registrator:master
    volumes:
        - "/var/run/docker.sock:/tmp/docker.sock"
