#
# Tyk api gateway
#
gateway:
    image: tykio/tyk-gateway:latest
    ports:
        - "80:8080"
        - "8080:8080"
    volumes:
        - ./tyk.conf:/opt/tyk-gateway/tyk.conf

#
# Tyk api gateway dashboard
#
dashboard:
    image: tykio/tyk-dashboard:latest
    ports:
        - "3000:3000"
    volumes:
        - ./tyk_analytics.conf:/opt/tyk-dashboard/tyk_analytics.conf

